/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectNewImport } from './routes/project/new'
import { Route as MapLayoutImport } from './routes/map/_layout'
import { Route as MapLayoutMapIdImport } from './routes/map/_layout.$mapId'

// Create Virtual Routes

const MapImport = createFileRoute('/map')()

// Create/Update Routes

const MapRoute = MapImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectNewRoute = ProjectNewImport.update({
  id: '/project/new',
  path: '/project/new',
  getParentRoute: () => rootRoute,
} as any)

const MapLayoutRoute = MapLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => MapRoute,
} as any)

const MapLayoutMapIdRoute = MapLayoutMapIdImport.update({
  id: '/$mapId',
  path: '/$mapId',
  getParentRoute: () => MapLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapImport
      parentRoute: typeof rootRoute
    }
    '/map/_layout': {
      id: '/map/_layout'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapLayoutImport
      parentRoute: typeof MapRoute
    }
    '/project/new': {
      id: '/project/new'
      path: '/project/new'
      fullPath: '/project/new'
      preLoaderRoute: typeof ProjectNewImport
      parentRoute: typeof rootRoute
    }
    '/map/_layout/$mapId': {
      id: '/map/_layout/$mapId'
      path: '/$mapId'
      fullPath: '/map/$mapId'
      preLoaderRoute: typeof MapLayoutMapIdImport
      parentRoute: typeof MapLayoutImport
    }
  }
}

// Create and export the route tree

interface MapLayoutRouteChildren {
  MapLayoutMapIdRoute: typeof MapLayoutMapIdRoute
}

const MapLayoutRouteChildren: MapLayoutRouteChildren = {
  MapLayoutMapIdRoute: MapLayoutMapIdRoute,
}

const MapLayoutRouteWithChildren = MapLayoutRoute._addFileChildren(
  MapLayoutRouteChildren,
)

interface MapRouteChildren {
  MapLayoutRoute: typeof MapLayoutRouteWithChildren
}

const MapRouteChildren: MapRouteChildren = {
  MapLayoutRoute: MapLayoutRouteWithChildren,
}

const MapRouteWithChildren = MapRoute._addFileChildren(MapRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapLayoutRouteWithChildren
  '/project/new': typeof ProjectNewRoute
  '/map/$mapId': typeof MapLayoutMapIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapLayoutRouteWithChildren
  '/project/new': typeof ProjectNewRoute
  '/map/$mapId': typeof MapLayoutMapIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/map': typeof MapRouteWithChildren
  '/map/_layout': typeof MapLayoutRouteWithChildren
  '/project/new': typeof ProjectNewRoute
  '/map/_layout/$mapId': typeof MapLayoutMapIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/map' | '/project/new' | '/map/$mapId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/map' | '/project/new' | '/map/$mapId'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/map/_layout'
    | '/project/new'
    | '/map/_layout/$mapId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRouteWithChildren
  ProjectNewRoute: typeof ProjectNewRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRouteWithChildren,
  ProjectNewRoute: ProjectNewRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/map",
        "/project/new"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/map": {
      "filePath": "map",
      "children": [
        "/map/_layout"
      ]
    },
    "/map/_layout": {
      "filePath": "map/_layout.tsx",
      "parent": "/map",
      "children": [
        "/map/_layout/$mapId"
      ]
    },
    "/project/new": {
      "filePath": "project/new.tsx"
    },
    "/map/_layout/$mapId": {
      "filePath": "map/_layout.$mapId.tsx",
      "parent": "/map/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
