/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectNewImport } from './routes/project/new'
import { Route as MapLayoutImport } from './routes/map/_layout'
import { Route as ProjectProjectIdLayoutImport } from './routes/project/$projectId/_layout'
import { Route as MapLayoutMapIdImport } from './routes/map/_layout.$mapId'
import { Route as ProjectProjectIdLayoutRunAnalysisImport } from './routes/project/$projectId/_layout.run-analysis'
import { Route as ProjectProjectIdLayoutResultsImport } from './routes/project/$projectId/_layout.results'
import { Route as ProjectProjectIdLayoutFilesImport } from './routes/project/$projectId/_layout.files'

// Create Virtual Routes

const MapImport = createFileRoute('/map')()
const ProjectProjectIdImport = createFileRoute('/project/$projectId')()

// Create/Update Routes

const MapRoute = MapImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectProjectIdRoute = ProjectProjectIdImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRoute,
} as any)

const ProjectNewRoute = ProjectNewImport.update({
  id: '/project/new',
  path: '/project/new',
  getParentRoute: () => rootRoute,
} as any)

const MapLayoutRoute = MapLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => MapRoute,
} as any)

const ProjectProjectIdLayoutRoute = ProjectProjectIdLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)

const MapLayoutMapIdRoute = MapLayoutMapIdImport.update({
  id: '/$mapId',
  path: '/$mapId',
  getParentRoute: () => MapLayoutRoute,
} as any)

const ProjectProjectIdLayoutRunAnalysisRoute =
  ProjectProjectIdLayoutRunAnalysisImport.update({
    id: '/run-analysis',
    path: '/run-analysis',
    getParentRoute: () => ProjectProjectIdLayoutRoute,
  } as any)

const ProjectProjectIdLayoutResultsRoute =
  ProjectProjectIdLayoutResultsImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => ProjectProjectIdLayoutRoute,
  } as any)

const ProjectProjectIdLayoutFilesRoute =
  ProjectProjectIdLayoutFilesImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => ProjectProjectIdLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapImport
      parentRoute: typeof rootRoute
    }
    '/map/_layout': {
      id: '/map/_layout'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapLayoutImport
      parentRoute: typeof MapRoute
    }
    '/project/new': {
      id: '/project/new'
      path: '/project/new'
      fullPath: '/project/new'
      preLoaderRoute: typeof ProjectNewImport
      parentRoute: typeof rootRoute
    }
    '/map/_layout/$mapId': {
      id: '/map/_layout/$mapId'
      path: '/$mapId'
      fullPath: '/map/$mapId'
      preLoaderRoute: typeof MapLayoutMapIdImport
      parentRoute: typeof MapLayoutImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdImport
      parentRoute: typeof rootRoute
    }
    '/project/$projectId/_layout': {
      id: '/project/$projectId/_layout'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdLayoutImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/_layout/files': {
      id: '/project/$projectId/_layout/files'
      path: '/files'
      fullPath: '/project/$projectId/files'
      preLoaderRoute: typeof ProjectProjectIdLayoutFilesImport
      parentRoute: typeof ProjectProjectIdLayoutImport
    }
    '/project/$projectId/_layout/results': {
      id: '/project/$projectId/_layout/results'
      path: '/results'
      fullPath: '/project/$projectId/results'
      preLoaderRoute: typeof ProjectProjectIdLayoutResultsImport
      parentRoute: typeof ProjectProjectIdLayoutImport
    }
    '/project/$projectId/_layout/run-analysis': {
      id: '/project/$projectId/_layout/run-analysis'
      path: '/run-analysis'
      fullPath: '/project/$projectId/run-analysis'
      preLoaderRoute: typeof ProjectProjectIdLayoutRunAnalysisImport
      parentRoute: typeof ProjectProjectIdLayoutImport
    }
  }
}

// Create and export the route tree

interface MapLayoutRouteChildren {
  MapLayoutMapIdRoute: typeof MapLayoutMapIdRoute
}

const MapLayoutRouteChildren: MapLayoutRouteChildren = {
  MapLayoutMapIdRoute: MapLayoutMapIdRoute,
}

const MapLayoutRouteWithChildren = MapLayoutRoute._addFileChildren(
  MapLayoutRouteChildren,
)

interface MapRouteChildren {
  MapLayoutRoute: typeof MapLayoutRouteWithChildren
}

const MapRouteChildren: MapRouteChildren = {
  MapLayoutRoute: MapLayoutRouteWithChildren,
}

const MapRouteWithChildren = MapRoute._addFileChildren(MapRouteChildren)

interface ProjectProjectIdLayoutRouteChildren {
  ProjectProjectIdLayoutFilesRoute: typeof ProjectProjectIdLayoutFilesRoute
  ProjectProjectIdLayoutResultsRoute: typeof ProjectProjectIdLayoutResultsRoute
  ProjectProjectIdLayoutRunAnalysisRoute: typeof ProjectProjectIdLayoutRunAnalysisRoute
}

const ProjectProjectIdLayoutRouteChildren: ProjectProjectIdLayoutRouteChildren =
  {
    ProjectProjectIdLayoutFilesRoute: ProjectProjectIdLayoutFilesRoute,
    ProjectProjectIdLayoutResultsRoute: ProjectProjectIdLayoutResultsRoute,
    ProjectProjectIdLayoutRunAnalysisRoute:
      ProjectProjectIdLayoutRunAnalysisRoute,
  }

const ProjectProjectIdLayoutRouteWithChildren =
  ProjectProjectIdLayoutRoute._addFileChildren(
    ProjectProjectIdLayoutRouteChildren,
  )

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdLayoutRoute: typeof ProjectProjectIdLayoutRouteWithChildren
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdLayoutRoute: ProjectProjectIdLayoutRouteWithChildren,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapLayoutRouteWithChildren
  '/project/new': typeof ProjectNewRoute
  '/map/$mapId': typeof MapLayoutMapIdRoute
  '/project/$projectId': typeof ProjectProjectIdLayoutRouteWithChildren
  '/project/$projectId/files': typeof ProjectProjectIdLayoutFilesRoute
  '/project/$projectId/results': typeof ProjectProjectIdLayoutResultsRoute
  '/project/$projectId/run-analysis': typeof ProjectProjectIdLayoutRunAnalysisRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapLayoutRouteWithChildren
  '/project/new': typeof ProjectNewRoute
  '/map/$mapId': typeof MapLayoutMapIdRoute
  '/project/$projectId': typeof ProjectProjectIdLayoutRouteWithChildren
  '/project/$projectId/files': typeof ProjectProjectIdLayoutFilesRoute
  '/project/$projectId/results': typeof ProjectProjectIdLayoutResultsRoute
  '/project/$projectId/run-analysis': typeof ProjectProjectIdLayoutRunAnalysisRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/map': typeof MapRouteWithChildren
  '/map/_layout': typeof MapLayoutRouteWithChildren
  '/project/new': typeof ProjectNewRoute
  '/map/_layout/$mapId': typeof MapLayoutMapIdRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/_layout': typeof ProjectProjectIdLayoutRouteWithChildren
  '/project/$projectId/_layout/files': typeof ProjectProjectIdLayoutFilesRoute
  '/project/$projectId/_layout/results': typeof ProjectProjectIdLayoutResultsRoute
  '/project/$projectId/_layout/run-analysis': typeof ProjectProjectIdLayoutRunAnalysisRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map'
    | '/project/new'
    | '/map/$mapId'
    | '/project/$projectId'
    | '/project/$projectId/files'
    | '/project/$projectId/results'
    | '/project/$projectId/run-analysis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map'
    | '/project/new'
    | '/map/$mapId'
    | '/project/$projectId'
    | '/project/$projectId/files'
    | '/project/$projectId/results'
    | '/project/$projectId/run-analysis'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/map/_layout'
    | '/project/new'
    | '/map/_layout/$mapId'
    | '/project/$projectId'
    | '/project/$projectId/_layout'
    | '/project/$projectId/_layout/files'
    | '/project/$projectId/_layout/results'
    | '/project/$projectId/_layout/run-analysis'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRouteWithChildren
  ProjectNewRoute: typeof ProjectNewRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRouteWithChildren,
  ProjectNewRoute: ProjectNewRoute,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/map",
        "/project/new",
        "/project/$projectId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/map": {
      "filePath": "map",
      "children": [
        "/map/_layout"
      ]
    },
    "/map/_layout": {
      "filePath": "map/_layout.tsx",
      "parent": "/map",
      "children": [
        "/map/_layout/$mapId"
      ]
    },
    "/project/new": {
      "filePath": "project/new.tsx"
    },
    "/map/_layout/$mapId": {
      "filePath": "map/_layout.$mapId.tsx",
      "parent": "/map/_layout"
    },
    "/project/$projectId": {
      "filePath": "project/$projectId",
      "children": [
        "/project/$projectId/_layout"
      ]
    },
    "/project/$projectId/_layout": {
      "filePath": "project/$projectId/_layout.tsx",
      "parent": "/project/$projectId",
      "children": [
        "/project/$projectId/_layout/files",
        "/project/$projectId/_layout/results",
        "/project/$projectId/_layout/run-analysis"
      ]
    },
    "/project/$projectId/_layout/files": {
      "filePath": "project/$projectId/_layout.files.tsx",
      "parent": "/project/$projectId/_layout"
    },
    "/project/$projectId/_layout/results": {
      "filePath": "project/$projectId/_layout.results.tsx",
      "parent": "/project/$projectId/_layout"
    },
    "/project/$projectId/_layout/run-analysis": {
      "filePath": "project/$projectId/_layout.run-analysis.tsx",
      "parent": "/project/$projectId/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
